1_Two_Sum/shouwang.c, 258_Add_Digits/258_Add_Digits.c, 2_Add_Two_Numbers/shouwang.c, 344_Reverse_String/shouwang.c, 461_Hamming_Distance/461_Hamming_Distance.c, 476_Number_Complement/shouwang.c, 540_Single_Element_in_a_Sorted_Array/shouwang.c
=> add 4 leetcode answers

26_remove_duplicates_from_sorted_array/26_remove_duplicates_from_sorted_array.c, 83_remove_duplicates_from_sorted_list/83_remove_duplicates_from_sorted_list.cpp
2018年10月8日领扣刷题代码：
26_remove_duplicates_from_sorted_array  and  83_remove_duplicates_from_sorted_list
form barowwang
=> 提交2018年10月8日领扣刷题代码

26_remove_duplicates_from_sorted_array/26_Rocky's_solution.c, 83_remove_duplicates_from_sorted_list/83_Rocky's_solution.c
=> Add my solutions to #26 and #83

0204_Count_Primes/alvis.c
[Prime count] Init Version
from Alvis
=> [Prime Count] init version

0263_Ugly_Number/alvis.c
[0263 Ugly Number] Init Verson
=> [0263 Ugly Number] Init Verson

0005_Longest_Palindromic_Substring/alvis.py
=> [ 0005 Longest Palindromic Substring] init version, time exceeded

0405_Convert_a_Number_to_Hexadecimal/nicefuture.c
=> Solution: 405

0234_Palindrome_Linked_List/Palindrome_Linked_List.cpp
=> 0234_Palindrome_Linked_List

012 Integer to Roman/012_Integer to Roman.cpp
https://leetcode.com/problems/integer-to-roman/description/
=> the website about the detail for the problem

0234_Palindrome_Linked_List/0234PalindromeLinkedList1.cpp
=> “add 0234PalindromeLinkedList1.cpp”

0234_Palindrome_Linked_List/Palindrome.java
* 先让链表的一半元素入栈，再对剩余的元素和堆栈中的元素做比较
=> 回文数组，使用栈解决。

0002_Add_Two_Numbers/pingtou.cpp
Dear Avlin,
i made a changing for "0002_Add_Two_Numbers" practice.Please check it and merge it.TKS!
=> pingtou add pingtou.cpp for hamming distance.

0001_Two_Sum/dahai.js
Dear alvin
I have two sum commit,please merge it
=> 0001tosum submit

0026_Remove_Duplicates_from_Sorted_Array/zchaos.cpp
良许LeetCode刷题群
微信:张小胖
添加0026：Remove Duplicates from Sorted Array
=> zchaos(wx:张小胖) add zchaos.cpp

0200_Number_Islands/numIslands.py
=> Xiazheteng add 200

0771_Jewels_And_Stones/JewelsAndStones.java, 0771_Jewels_And_Stones/【LeetCode题解---771】Jewels and Stones.md
=> 771 JewelsAndStones

0234_Palindrome_Linked_List/paLinkedList_234.py, 0234_Palindrome_Linked_List/palindromeLinkedList_234.py
=> 判断单链表是否为回文序列

0400_Nth_Digit/Solution.java
良许大大,这道题我一开始不会做,看了别人的思路,重新做出来的
微信名 璃
=> deadlyAce add Solution.java

0234_Palindrome_Linked_List/ListNode.java
=> 回文链表，微信号：徐祖海

0001_Two_Sum/persiststudy.py
Hello Alvin,
0001_Two_Sum by persiststudy with python.
The first commit in your git hub about leetcode.
Weixinhao: Benny6599.
=> 0001_Two_Sum by persiststudy with python

0268_Missing_Number/missing_number_by_Rocky.c, 0374_Guess_Number_Higher_or_Lower/guess_number_by_Rocky.java, 0400_Nth_Digit/Nth_Digit_by_Rocky.c
=> Add my solutions to 0268, 0374 and 0400. (wechat: Rocky)

0206_Reverse_Linked_List_Java/ListNode.java, 0206_Reverse_Linked_List_Java/ReverseLinkNode.java, 0206_Reverse_Linked_List_Java/Test.java
Dear alvin:
At the beginning, I chose an easier question, and I will slowly strengthen it later. Thank you for providing this platform.
=> 0206Reverse_Linked_List

0017_Letter_Combinations_of_a_Phone_Number/Letter combination.py
LeetCode Num.17 '电话号码的字母组合'
Author : Vodka
=> Vodka add 0017_Letter_Combinations_of_a_Phone_Number

0092_Reverse_Linked_List_II/mysolution.py
Divided into three situations and starting reversing.
(nickname--zhazha)
=> ugly solution

0039_Combination_Sum/Test.java
=> My name is Endeavor

.gitignore, 0007_Reverse_Integer/yrpang.c
add an answer to 0007_Reverse_Integer.
=> add an answer to 0007

0905_Sort_Array_By_Parity/persiststudy.c
Hello Alvin,
0905_Sort_Array_By_Parity by persiststudy with c
nickname:文渊
weixin:Benny6599
=> 0905_Sort_Array_By_Parity by persiststudy with c

0905_Sort_Array_By_Parity/Solution.java
=> 创建0905，提交一次代码：流星

0092_Reverse_Linked_List_II/reverse_linked_list.py
=> 时文1998 adds reverse_linked_list.py

0125_Valid_Palindrome/0125_Valid_Palindrome.py
=> Nian add 0125_Valid_Palindrome

0905_Sort_Array_By_Parity/Sort Array By Parity_prtea-ban.py
=> protea-ban add 905

0387_First_Unique_Character_in_a_String/FirstUniqueChar.java
=> 给定一个字符串，找到它的第一个不重复的字符，并返回它的索引。如果不存在，则返回 -1。

0056_Merge_Intervals/Merge Intervals.py
=> Merge Intervals.py

0905_Sort_Array_By_Parity/SortArray.java
=> ace add SortArray.java

0056_Merge_Intervals/leetcode056.py, 0905_Sort_Array_By_Parity/leetcode905.py, 0905_Sort_Array_By_Parity/new_leetcode905.py
By_ricardo
刚刚那个缩进错了，我把缩进改了一下重新交！
=> NO.0905_Sort_Array

0009_Palindrome_Number/yrpang.c
Vincent's answer of 0009_Palindrome_Number
=> Vincent 0009_Palindrome_Number

0206_Reverse_Linked_List_Java_递归/ListNode.java, 0206_Reverse_Linked_List_Java_递归/ReverseLinkNode.java, 0206_Reverse_Linked_List_Java_递归/Test.java
=> 0206单链表反转Java_递归

0001_Two_Sum/annjeff.cpp
=> annjeff write a file named annjeff.cpp

0001_Two_Sum/xifenghuyang.java, 0002_Add_Two_Numbers/xifenghuyang.java
xifenghuyang
向大神学习，提高执行能力。
2018/11/18
=> xifenghuyang

0002_Add_Two_Numbers/HowieLee.java
=> Howie Lee (lihaoyuan0518)

0476_Number_Complement/0476_Number_Complement_Rocky.c, 0739_Daily_Temperatures/0739_Daily_Temperatures_Rocky.c
476数字的补数程序耗时4ms
739每日温度程序耗时最短72ms
=> Add my solutions to 0476 and 0739 (wechat: Rocky)

0213_House_Robber_II/solution.py
A funny dynamic problems!(Nickname: zhazha)
=> DP problems

0001_Two_Sum/my_first_code.py
=> my_first_code

0905_Sort_Array_By_Parity/Solution.java, 0905_Sort_Array_By_Parity/SortArrayByParity.java
=> 905-按奇偶排序数组，微信号：lionfly

0003_Longest_Substring_Without_Repeating_Characters/nicefuture.java, 0004_Median_of_Two_Sorted_Arrays/nicefuture.java
add solution: 0003 [by nicefuture].
=> add solution: 0003 [by nicefuture].

0018_4Sum/recursive.py, summary_2018_47.txt
Solve 4Sum by recursively reducing to 2Sum.
=> recursive solution for 4Sum

0704_Binary_Search/0704_Binary_Search_by_persiststudy.c, summary_2018_47.txt
Hello Alvin
0704_Binary_Search by persiststudy with C and update summary file.
=> 0704_Binary_Search by persiststudy with C and update summary file

0053_Maximum_Subarray/fengdongsheng.cpp, summary_2018_47.txt
=> fengdongdong

0008_String_to_Integer_(atoi)/zchaos.cpp, submittors/张小胖.txt
=> 来自良许leetcode刷题群 张小胖

0015_3Sum/3Sum.cpp, 0015_3Sum/3Sum2.cpp, 0018_4Sum/4Sum.cpp, 0027_Remove_Element/Remove_Element.cpp, 0027_Remove_Element/Remove_Element2.cpp, 0027_Remove_Element/Remove_Element3.cpp, 0028_Implement_strStr/Implement_strStr().cpp, 0028_Implement_strStr/Implement_strStr()2.cpp, 0028_Implement_strStr/Implement_strStr()3.cpp, 0080_Remove_Duplicates_from_Sorted_Array_II/Remove_Duplicates_from_Sorted_Array_II.cpp, 0080_Remove_Duplicates_from_Sorted_Array_II/Remove_Duplicates_from_Sorted_Array_II2.cpp
Hi, Aivin
Code commission of this week. Have a nice day! 
MQQM
2018.11.24
=> Problem 15, 18, 27 and 80. 

0001_Two_Sum_Java/Test0001.java, summary_2018_47.txt
=> 0001_Two_Sum_Java

0002_Add_Two_Numbers/add_two.py
时文1998  2ef9554c1fbc564912820ebf4e4ff19a2afa20af
=> 时文1998 add add_two.py

0018_4Sum/Sum_of_4number.c
=> si shui liu nian commit

0027_Remove_Element/Remove_Element4.cpp, submittors/素锦年华.txt
1.add Remove_Element4.cpp
2.add submittors/素锦年华.txt
=> add leetcode 0027 by yangwx2904

0061_List_Rotate/the_second.cpp
=> the_second.cpp

0890_Find_And_Replace_Pattern/0890_Find_And_Replace_PatternbyDecadence.c, submittors/Decadence.txt
=> Decadence'first commit 890

0788_Rotated_Digits/0788_yang.py, 0890_Find_And_Replace_Pattern/0890_yang.py
=> leetcode 0788 and 0890

0788_Rotated_Digits/RotatedDigits_788.java, 0890_Find_And_Replace_Pattern/FindandReplacePattern_890.java
Ashbringer   20181130  commit  0788 and 0890
=> Ashbringer 20181130commit

0788_Rotated_Digits/zwalker.py, 0890_Find_And_Replace_Pattern/zwalker1.py
=> zwalker add zwalker.py and zwalker1.py

0003_Longest_Substring_Without_Repeating_Characters/LongestSubstringWithoutRepeatingCharacters.cpp, submittors/素锦年华.txt
add LongestSubstringWithoutrepeatingCharters.cpp by yangwx2904
add subnittors/素锦年华.txt
=>  add LongestSubstringWithoutrepeatingCharters.cpp by yangwx2904

0020_Valid_Parentheses/yrpang1.c, submittors/yrpang.txt
add another answer to 0020 with C
=> add another answer to 0020

0002_Add_Two_Numbers/vino.cpp, submittors/vino.txt
=> add by vino

0021_Merge_Two_Sorted_Lists/MergeTwoSortedLists.java, MergeTwoSortedLists.java, submittors/chenghui.txt
This file is added by Chenghui
=> add MergeTwoSortedLists.java

0101_Symmetric_Tree/Solution_101.java
=> leetcode_101_22k

0109_Convert_Sorted_List_to_Binary_Search_Tree/ConvertSortedListtoBinarySearchTree_109.java, 0215_Kth_Largest_Element_in_an_Array/KthLargestElementinanArray_215.java, submittors/Ashbringer.txt
Ashbringer commit ID aa5465ddaf3f7c011555fec0c23cace04ecdb5fa
=> Ashbringer commit ID aa5465ddaf3f7c011555fec0c23cace04ecdb5fa 

0001_Two_Sum/seaflower.go
=> 0001 Two Sum use golang

0002_Add_Two_Numbers/seaflower.go
=> Add two numbers

0003_Longest_Substring_Without_Repeating_Characters/seaflower.go
Add  LengthOfLongestSubstring golang版本
=> Length of longest substring

0004_Median_of_Two_Sorted_Arrays/seaflower.go
Add Median of Two Sorted Arrays golang
=> Add Median of Two Sorted Arrays golang

0005_Longest_Palindromic_Substring/seaflower.go
Add Longest Palindromic Substring  by golang
=> Add Longest Palindromic Substring by golang

0006_ZigZag_Conversion/seaflower.go
=> [WIP]: leetCodeNo6 use golang

problems/0005_Longest_Palindromic_Substring/chengyu.cpp, submittors/石成玉
=> The first week

problems/0021_Merge_Two_Sorted_Lists/merwin_21.java, problems/0024_Swap_Nodes_in_Pairs/merwin_24.java
Dear Alvin,
I have committed two problem's solution.
=> 21,24 merwinlin

problems/0448_Find_All_Numbers_Disappeared_in_an_Array/dachuan.java, submittors/大船.txt
commit 0448_Find_All_Numbers_Disappeared_in_an_Array by dachuan.
=>  finish this week's work on 20190307.

problems/0003_Longest_Substring_Without_Repeating_Characters/lalala.c, submittors/啦啦啦.txt
=> wechat：啦啦啦

problems/0020_Valid_Parentheses/merwin_20.java, problems/0070_Climbing_Stairs/merwin_70.java
Dear Alvin，
I committed two solutions.
=> 20 70 merwinlin

problems/0007_Reverse_Integer/seaflower.go
=> Add Reverse Integer by golang 

problems/0008_String_to_Integer_atoi/seaflower.go
=> add myatoi leetcode No8

problems/0566_Reshape the Matrix/566.cpp, submittors/abel.c
=> The third week

problems/0003_Longest_Substring_Without_Repeating_Characters/Lonecloud.java, submittors/lonecloud.md
=> three week

problems/0002_Add_Two_Numbers/Ashbringer.java, problems/0110_Balanced_Binary_Tree/Ashbringer.java, problems/0257_binary_tree_paths/Ashbringer.java, submittors/Ashbringer.txt
7babc8dc0e6ab33b01ed3a40b0e96f10f31138ea
=> Ashbringer commit id 7babc8dc0e6ab33b01ed3a40b0e96f10f31138ea

problems/0028_Implement_strStr/merwin_28.java, problems/0125_Valid_Palindrome/merwin_125.java
Hi
commit solutions of 28 and 125
=> 28 125 merwinlin

problems/0009_Palindrome_Number/seaflower.go
=> Add leetCodeNo9 use golang

problems/0046_Permutations/merwin_46.java, problems/0073_Set_Matrix_Zeroes/merwin_73.java
=> 46 73 merwinlin

problems/0001_Two_Sum/ass.cpp, submittors/ass-1.c
=> first week

problems/0263_Ugly_Number/solution.py, problems/0264_ugly-number-ii/solution.py, submittors/lionfly.txt
=> 0263_and_0264

problems/0001_Two_Sum/h_twosum.cpp, problems/0152_Maximum_Product_Subarray/h_Maximum_Product_Subarray.cpp, submittors/种一棵树-1.c, submittors/种一棵树-2.c
你好良许，这是我的打卡提交，微信ID：种一棵树
需要说明的是，我把题解放到problems/中，然后直接commit的整个problems/文件夹，所以两道题一个commitID。
第一次玩git，不太熟练，希望后面可以好一点。
祝好！
=> leetcode 打卡

problems/0019_Remove_Nth_Node_From_End_of_List/一碗机智的糖浆.java, problems/0141_Linked_List_Cycle/一碗机智的糖浆.java
=> 一碗机智的糖浆0019，0141

problems/0010_Regular_Expression_Matching/seaflower.go
=> add leetcode No.10

problems/0007_Reverse_Integer/zero.java, problems/0009_Palindrome_Number/zero.java, submittors/zero.txt
Dear Alvin,
I add 0007_Reverse_Integer and 0009_Palindrome_Number,please merge it ,thx!
=> add 0007_Reverse_Integer and 0009_Palindrome_Number

problems/0013_Roman_to_Integer/zero.java, problems/0014_Longest_Common_Prefix/zero.java, submittors/zero.txt
Dear yychuyu,
I add 0013_Roman_to_Integer and 0014_Longest_Common_Prefix,please merge it,thx!
=> add 0013_Roman_to_Integer and 0014_Longest_Common_Prefix

problems/0005_Longest_Palindromic_Substring/solution.py, problems/0769_Max_Chunks_To_Sorted/solution.py, submittors/lionfly.txt
=> 0005 and 0769

problems/0011_Container_With_Most_Water/seaflower.go
=> Add LeetCode No11

problems/0013_Roman_to_Integer/seaflower.go
=> Add LeetCode No.13 use golang

problems/0012_Integer_to_Roman/seaflower.go
=> Add LeetCode No.12 use golang

problems/0200_Number_Islands/bbj.cpp, problems/0202_Happy_Number/bbj.cpp, submittors/棒棒鸡不棒-1.cpp, submittors/棒棒鸡不棒-2.cpp
=> solutions for the fourth week

problems/0014_Longest_Common_Prefix/seaflower.go
=> Add LeetCodeNo14 use golang

problems/0566_Reshape_the_Matrix/21_no566.py, problems/0995_Sort_Array_By_Parity/21_no995.py
upload 21_charlie LeetCode No.566
=> add 566 by 21_charlie

problems/0217_Contains_Duplicate/217_charlie.py
=> add 217 from 21_charlie

problems/0015_3Sum/seaflower.go
=> Add LeetCode No15

problems/1021_Remove_Outermost_Parentheses/21_charlie.py
=> add 1021 from 21_charlie

problems/0001_Two_Sum/26逝水流.js, problems/0415_Add_Strings/26逝水流.js
add 1.two_sum
add 415.add_strings
=> add 1/two_sum
